name: psetw-publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install addititional tools
        shell: pwsh
        run: |
          Install-Module -Name platyPS -Scope CurrentUser
          Import-Module platyPS
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: dotnet publish
        run: dotnet publish -c Release -o "./psetwquery"
      - name: build help files
        run: |
          Import-Module ./psetwquery -Force
          New-ExternalHelp ./docs -OutputPath ./psetwquery/en-US/
        shell: pwsh
      - name: psgallery publish
        run: |
          $env:GITHUB_WORKSPACE
          Publish-Module -Path "./psetwquery" -NuGetApiKey ${{ secrets.PS_GALLERY_SECRET }}
        shell: pwsh
        